### ISSUE TITLE
Very good code style

### ISSUE THREAD

**Issue by ice1000** [ProgramLeague/SecMail#1]
Your code style is really nice! :+1: 
N I wonder the TODO you've mentioned in your commit, I didn't see any TODO in Main.Send?

You solved it yourself?

P.S. I can help with the Android client(please provide API, it must be MVC)

**Comment by ice1000** [comment]
It seems that U have nothing 2 say 2 my issue.
So I just unstar this repo. :-1:

**Comment by lizhaohan001** [comment]
Sorry that I didn't reply you. :-)
The TODO isn't in Mail.Send, it's in Mail.Get. (Blame on me) and I fixed it by my self in [902757b].(https://github.com/ProgramLeague/SecMail/commit/902757b0bc5b02a60e9e5271368c93ca401a2343)

**Comment by ice1000** [comment]
>_>
That's good.
